apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  # name of template, convention is to use the repo name of the template
  name: Barnacle Integration 
  # title for prettier display on the template catalog
  title: (Beta) Cybersecurity Defense Engineering Barnacle
  # description for prettier display on the template catalog
  description: This is a beta version of CDE manifest integration for GitHub
  # list of string tags used on the Template catalog for search-ability
  tags:
    - Security
    - Cyber Defense 
    - SAST&SCA

spec:
  owner: Cyber Defense Engineer
  type: Security

  parameters:
    - title: Barnacle Information
      description: |
                      ## &#10071; Important &#10071;
                      An email notification will be sent to the requester once you submit the request. For documentation, please refer to ...
      required:
        - ProductID
        - GithubRepositoryName
      properties:
        GithubRepositoryName:
          title: GitHub Repo Name
          description: Name of the github repository
          ui:field: ##
      
        ProductId:
          title: Company Product ID
          description: Product ID
          ui:field: 

    - title: Application Details
      properties:
        appBuild:
          title: Application Build Type
          description: Build type includes - add here
          type: string
          enum:
            - Python-3.10
            - Node
            - Maven-3-jdk11
            - MAven-3-jdk22
            - Gradle
            - Ruby
          enumNames:
            - 'Python 3.10'
            - 'Node'
            - Maven-3-JDK11
            - Maven-3-JDK22
            - Gradle
            - Ruby
            
        comments:
          title: Any Comments and/or questions
          description: Brief and specific information you think will be helpful
          type: string
          ui:widget: textarea
          ui:options:
            rows: 4
      required:
        - GithubRepositoryName
        - appBuild

  steps:
    - id: Fetch Values
      name: Reading data submitted
      action: fetch:template
      input:
        url: ./skeleton
        values:
          employeeId:
          GithubRepositoryName: ${{ parameters.GithubRepositoryName.reponame? }}
          appBuild: ${{ parameters.appBuild }}
          comments: ${{ parameters.comments }}
