name: GitHub Security Scanning Workflow
on:
  workflow_call:
    inputs:
      product_id:
        type: string
        description: 'Product ID'
        required: true
        default: '123'
      
      scan_type:
        type: string
        description: 'Scan Type'
        required: true
        default: 'full'

jobs:
  lets_start_sculpting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Print Github Context 
        env:
          github_context: ${{ toJson(github) }}
        run: echo "$github_context"

      - name: Checkout Scanner Repository
        uses: actions/checkout@v4
        with:
          repository: rahulgauli/workflowtest
          path: scripts
          
      - name: Checkout python build
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run the script
        run: |
          pwd
          ls
          cd scripts/scripts
          ls
          python3 scanner.py >> $GITHUB_OUTPUT
          
          
          
          
